### ISSUE TITLE
Create new account page investigation

### ISSUE THREAD

**Issue by Thaewyn** [Thaewyn/operation-jungle-knight#10]
Investigate if we need a whole new 'create account' page, or if this can be handled as an attachment to the homepage.

In the event a new page is needed:

- [ ] new html file in pages
- [ ] new route in view_routes
- [ ] new link to page on index.html

**Comment by Fiskoal** [comment]
I believe registration should be handled on the homepage, (maybe modal or in the "game window") rather than having a unique create account page
